export const forms = [
  {
    id: 1,
    title: "Customer Satisfaction Survey",
    response: 128,
    questions: [
      { id: 1, question: "How would you rate our service?" },
      { id: 2, question: "Was the representative helpful?" },
      { id: 3, question: "How likely are you to recommend us?" },
      { id: 4, question: "What could we improve on?" },
      { id: 5, question: "Any additional comments?" },
      { id: 6, question: "How did you find our website?" },
      { id: 7, question: "Was the checkout process easy?" },
      { id: 8, question: "Did the product meet your expectations?" },
      { id: 9, question: "How was the shipping speed?" },
      { id: 10, question: "Is the pricing fair?" },
      { id: 11, question: "Will you shop with us again?" },
    ],
  },
  {
    id: 2,
    title: "Event Registration",
    response: 45,
    questions: [
      { id: 1, question: "What is your full name?" },
      { id: 2, question: "Which session will you attend?" },
      { id: 3, question: "Do you have any dietary restrictions?" },
      { id: 4, question: "Will you require parking?" },
      { id: 5, question: "How did you hear about this event?" },
      { id: 6, question: "What is your shirt size?" },
      { id: 7, question: "Are you bringing a plus one?" },
      { id: 8, question: "Do you need accessibility accommodations?" },
      { id: 9, question: "Which workshop is your top priority?" },
      { id: 10, question: "Emergency contact name?" },
      { id: 11, question: "Emergency contact number?" },
      { id: 12, question: "Is this your first time attending?" },
    ],
  },
  {
    id: 3,
    title: "Website Feedback",
    response: 12,
    questions: [
      { id: 1, question: "Is the navigation intuitive?" },
      { id: 2, question: "Did the page load quickly?" },
      { id: 3, question: "Did you find what you were looking for?" },
      { id: 4, question: "Rate the visual design." },
      { id: 5, question: "Report any bugs found." },
      { id: 6, question: "What browser are you using?" },
      { id: 7, question: "Are the font sizes readable?" },
      { id: 8, question: "Is the search bar effective?" },
      { id: 9, question: "Would you prefer a dark mode?" },
      { id: 10, question: "Did the images load properly?" },
      { id: 11, question: "Rate the mobile experience." },
      { id: 12, question: "Is the contact information easy to find?" },
      { id: 13, question: "Any suggestions for the homepage?" },
    ],
  },
  {
    id: 4,
    title: "Employee Engagement",
    response: 89,
    questions: [
      { id: 1, question: "Do you feel valued at work?" },
      { id: 2, question: "Is your workload manageable?" },
      { id: 3, question: "Do you have the tools you need?" },
      { id: 4, question: "How is your relationship with your manager?" },
      { id: 5, question: "Would you refer a friend to work here?" },
      { id: 6, question: "Are the company goals clear?" },
      { id: 7, question: "Is the office environment comfortable?" },
      { id: 8, question: "Do you have growth opportunities?" },
      { id: 9, question: "Rate the internal communication." },
      { id: 10, question: "Is the remote work policy fair?" },
      { id: 11, question: "How do you rate team collaboration?" },
      { id: 12, question: "Are meetings productive?" },
      { id: 13, question: "Do you feel safe expressing opinions?" },
      { id: 14, question: "Rate your work-life balance." },
    ],
  },
  {
    id: 5,
    title: "Product Research",
    response: 210,
    questions: [
      { id: 1, question: "Which feature do you use most?" },
      { id: 2, question: "How often do you use the app?" },
      { id: 3, question: "What feature is missing?" },
      { id: 4, question: "Rate the ease of use." },
      { id: 5, question: "What is your primary goal with this product?" },
      { id: 6, question: "Compared to competitors, how do we rank?" },
      { id: 7, question: "Is the onboarding tutorial helpful?" },
      { id: 8, question: "How likely are you to renew your subscription?" },
      { id: 9, question: "Does the UI feel modern?" },
      { id: 10, question: "How do you rate the mobile app?" },
      { id: 11, question: "Is the customer support responsive?" },
      { id: 12, question: "Do you find the notifications annoying?" },
      { id: 13, question: "What is your favorite UI element?" },
      { id: 14, question: "How much time do you save using this?" },
      { id: 15, question: "Would you pay more for premium support?" },
    ],
  },
  {
    id: 6,
    title: "Market Research - Coffee Habits",
    response: 342,
    questions: [
      { id: 1, question: "How many cups of coffee do you drink daily?" },
      { id: 2, question: "What is your preferred brewing method?" },
      { id: 3, question: "Do you prefer specialty beans?" },
      { id: 4, question: "How much are you willing to pay for a latte?" },
      { id: 5, question: "Most important factor in a coffee shop?" },
      { id: 6, question: "Do you use milk alternatives?" },
      { id: 7, question: "Do you buy coffee beans for home?" },
      { id: 8, question: "Favorite coffee origin (e.g., Ethiopia)?" },
      { id: 9, question: "Do you prefer hot or iced coffee?" },
      { id: 10, question: "Do you visit cafes to work?" },
      { id: 11, question: "Is branding important to you?" },
    ],
  },
  {
    id: 7,
    title: "Software Beta Test Feedback",
    response: 56,
    questions: [
      { id: 1, question: "Did you encounter any crashes?" },
      { id: 2, question: "Which feature was hardest to find?" },
      { id: 3, question: "How would you rate the user interface?" },
      { id: 4, question: "Did the documentation answer your questions?" },
      { id: 5, question: "What is your #1 requested feature?" },
      { id: 6, question: "Was the installation process smooth?" },
      { id: 7, question: "Did you notice any performance lag?" },
      { id: 8, question: "Are the error messages helpful?" },
      { id: 9, question: "How likely are you to use this daily?" },
      { id: 10, question: "Did you test the API integration?" },
      { id: 11, question: "Rate the security features." },
      { id: 12, question: "Was the dark mode consistent?" },
    ],
  },
  {
    id: 8,
    title: "Neighborhood Safety Survey",
    response: 18,
    questions: [
      { id: 1, question: "Do you feel safe walking at night?" },
      { id: 2, question: "Is the street lighting adequate?" },
      { id: 3, question: "Increase in local traffic?" },
      { id: 4, question: "Do you know your immediate neighbors?" },
      { id: 5, question: "What should the HOA prioritize?" },
      { id: 6, question: "Are local parks well-maintained?" },
      { id: 7, question: "Do you support more security cameras?" },
      { id: 8, question: "Have you seen any suspicious activity?" },
      { id: 9, question: "How is the local police response?" },
      { id: 10, question: "Are sidewalks in good condition?" },
      { id: 11, question: "Rate the cleanliness of the streets." },
      { id: 12, question: "Is noise pollution an issue?" },
      { id: 13, question: "Do you use the community center?" },
    ],
  },
  {
    id: 9,
    title: "Workshop Exit Ticket",
    response: 29,
    questions: [
      { id: 1, question: "Most valuable thing learned?" },
      { id: 2, question: "Was the instructor's pace appropriate?" },
      { id: 3, question: "Were exercises helpful?" },
      { id: 4, question: "Topic to spend more time on?" },
      { id: 5, question: "Attend an advanced version?" },
      { id: 6, question: "Rate the workshop materials." },
      { id: 7, question: "Was the venue comfortable?" },
      { id: 8, question: "Did you have enough networking time?" },
      { id: 9, question: "How was the food/catering?" },
      { id: 10, question: "Was the Q&A session useful?" },
      { id: 11, question: "Will you apply these skills at work?" },
      { id: 12, question: "Overall rating out of 10?" },
      { id: 13, question: "How could we improve the slides?" },
      { id: 14, question: "Was the registration process easy?" },
    ],
  },
  {
    id: 10,
    title: "Subscription Cancellation Survey",
    response: 94,
    questions: [
      { id: 1, question: "Why are you leaving us today?" },
      { id: 2, question: "Was it too expensive?" },
      { id: 3, question: "Moving to a competitor?" },
      { id: 4, question: "What could we have done to keep you?" },
      { id: 5, question: "Contact you in the future?" },
      { id: 6, question: "How long were you a customer?" },
      { id: 7, question: "Did you use the core features?" },
      { id: 8, question: "Was the cancellation process easy?" },
      { id: 9, question: "Did you ever contact support?" },
      { id: 10, question: "Rate the product quality." },
      { id: 11, question: "Would you recommend us to others?" },
      { id: 12, question: "What was your least favorite part?" },
      { id: 13, question: "Did you find the emails helpful?" },
      { id: 14, question: "Are you switching to a free plan?" },
      { id: 15, question: "Final thoughts?" },
    ],
  },
  {
    id: 11,
    title: "Mobile App Gaming Habits",
    response: 512,
    questions: [
      { id: 1, question: "How many hours a week do you play?" },
      { id: 2, question: "Favorite game genre?" },
      { id: 3, question: "Do you make in-app purchases?" },
      { id: 4, question: "Preferred platform (iOS/Android)?" },
      { id: 5, question: "Is 'pay-to-win' a dealbreaker?" },
      { id: 6, question: "Do you play with friends?" },
      { id: 7, question: "Importance of graphics?" },
      { id: 8, question: "Rate the touch controls." },
      { id: 9, question: "Do you watch gaming ads?" },
      { id: 10, question: "Frequency of new game downloads?" },
      { id: 11, question: "Do you use a controller?" },
    ],
  },
  {
    id: 12,
    title: "Fitness & Nutrition Tracker",
    response: 304,
    questions: [
      { id: 1, question: "Do you track calories?" },
      { id: 2, question: "How many steps daily?" },
      { id: 3, question: "Favorite type of exercise?" },
      { id: 4, question: "Do you use a smartwatch?" },
      { id: 5, question: "Main fitness goal?" },
      { id: 6, question: "How many liters of water daily?" },
      { id: 7, question: "Do you follow a specific diet?" },
      { id: 8, question: "Rate your sleep quality." },
      { id: 9, question: "Do you take supplements?" },
      { id: 10, question: "How many rest days a week?" },
      { id: 11, question: "Do you meal prep?" },
      { id: 12, question: "Rate the app's food database." },
    ],
  },
  {
    id: 13,
    title: "Remote Work Preference Survey",
    response: 87,
    questions: [
      { id: 1, question: "Ideally, how many days at home?" },
      { id: 2, question: "Is your home office ergonomic?" },
      { id: 3, question: "Biggest remote work challenge?" },
      { id: 4, question: "Do you feel more productive?" },
      { id: 5, question: "Missing office social interactions?" },
      { id: 6, question: "Quality of home internet?" },
      { id: 7, question: "Do you use a VPN?" },
      { id: 8, question: "Frequency of video calls?" },
      { id: 9, question: "Preferred communication tool?" },
      { id: 10, question: "Does the company provide hardware?" },
      { id: 11, question: "Are working hours flexible?" },
      { id: 12, question: "Do you work from cafes?" },
      { id: 13, question: "Rate the virtual team building." },
    ],
  },
  {
    id: 14,
    title: "E-learning Platform Feedback",
    response: 156,
    questions: [
      { id: 1, question: "Are the video lessons clear?" },
      { id: 2, question: "Was the quiz difficulty fair?" },
      { id: 3, question: "Rate the mobile experience." },
      { id: 4, question: "Is the course certificate valuable?" },
      { id: 5, question: "Topic you want to see next?" },
      { id: 6, question: "Did the instructor respond to posts?" },
      { id: 7, question: "Was the course worth the price?" },
      { id: 8, question: "Rate the downloadable resources." },
      { id: 9, question: "Did you finish the course?" },
      { id: 10, question: "Is the platform easy to navigate?" },
      { id: 11, question: "Would you take another course?" },
      { id: 12, question: "Rate the community forum." },
      { id: 13, question: "Were the subtitles accurate?" },
      { id: 14, question: "How was the audio quality?" },
    ],
  },
  {
    id: 15,
    title: "Travel & Vacation Planner",
    response: 62,
  },
];
